/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Subject = IDL.Text;
export const Time = IDL.Int;
export const TimetableConfig = IDL.Record({
  'subjects' : IDL.Vec(Subject),
  'dailyStudyHours' : IDL.Nat,
  'subjectTimeSlots' : IDL.Vec(IDL.Tuple(Subject, Time)),
});
export const StudyTask = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'text' : IDL.Text,
  'completed' : IDL.Bool,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DayIntensity = IDL.Variant({
  'red' : IDL.Null,
  'gray' : IDL.Null,
  'green' : IDL.Null,
});
export const DailyCompletionStatus = IDL.Record({
  'status' : DayIntensity,
  'date' : IDL.Text,
});
export const ProgressStats = IDL.Record({
  'totalTasks' : IDL.Nat,
  'completedTasks' : IDL.Nat,
  'remainingTasks' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addSubject' : IDL.Func([Subject], [TimetableConfig], []),
  'addTask' : IDL.Func([IDL.Text, IDL.Text], [StudyTask], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteTask' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyCompletionStatus' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(DailyCompletionStatus)],
      ['query'],
    ),
  'getProgressStats' : IDL.Func(
      [IDL.Text, IDL.Text],
      [ProgressStats],
      ['query'],
    ),
  'getSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'getTasksForDate' : IDL.Func([IDL.Text], [IDL.Vec(StudyTask)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerUser' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleTaskCompletion' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Subject = IDL.Text;
  const Time = IDL.Int;
  const TimetableConfig = IDL.Record({
    'subjects' : IDL.Vec(Subject),
    'dailyStudyHours' : IDL.Nat,
    'subjectTimeSlots' : IDL.Vec(IDL.Tuple(Subject, Time)),
  });
  const StudyTask = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'text' : IDL.Text,
    'completed' : IDL.Bool,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DayIntensity = IDL.Variant({
    'red' : IDL.Null,
    'gray' : IDL.Null,
    'green' : IDL.Null,
  });
  const DailyCompletionStatus = IDL.Record({
    'status' : DayIntensity,
    'date' : IDL.Text,
  });
  const ProgressStats = IDL.Record({
    'totalTasks' : IDL.Nat,
    'completedTasks' : IDL.Nat,
    'remainingTasks' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addSubject' : IDL.Func([Subject], [TimetableConfig], []),
    'addTask' : IDL.Func([IDL.Text, IDL.Text], [StudyTask], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteTask' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyCompletionStatus' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(DailyCompletionStatus)],
        ['query'],
      ),
    'getProgressStats' : IDL.Func(
        [IDL.Text, IDL.Text],
        [ProgressStats],
        ['query'],
      ),
    'getSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'getTasksForDate' : IDL.Func([IDL.Text], [IDL.Vec(StudyTask)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerUser' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleTaskCompletion' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };