/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DailyCompletionStatus {
  'status' : DayIntensity,
  'date' : string,
}
export type DayIntensity = { 'red' : null } |
  { 'gray' : null } |
  { 'green' : null };
export interface ProgressStats {
  'totalTasks' : bigint,
  'completedTasks' : bigint,
  'remainingTasks' : bigint,
}
export interface StudyTask {
  'id' : bigint,
  'date' : string,
  'text' : string,
  'completed' : boolean,
}
export type Subject = string;
export type Time = bigint;
export interface TimetableConfig {
  'subjects' : Array<Subject>,
  'dailyStudyHours' : bigint,
  'subjectTimeSlots' : Array<[Subject, Time]>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addSubject' : ActorMethod<[Subject], TimetableConfig>,
  'addTask' : ActorMethod<[string, string], StudyTask>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteTask' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailyCompletionStatus' : ActorMethod<
    [bigint, bigint],
    Array<DailyCompletionStatus>
  >,
  'getProgressStats' : ActorMethod<[string, string], ProgressStats>,
  'getSubjects' : ActorMethod<[], Array<Subject>>,
  'getTasksForDate' : ActorMethod<[string], Array<StudyTask>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerUser' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'toggleTaskCompletion' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];